#!/usr/bin/env python3
"""Deterministic artist-os -> JarvisAbleton adapter.

This adapter intentionally avoids Gemini, voice, research, or planning code.
It accepts a request JSON generated by artist-os, performs a narrow deterministic
Ableton preparation flow, and writes a result JSON.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

SCHEMA_VERSION_REQUEST = "artist-os/jarvis-ableton-request.v1"
SCHEMA_VERSION_RESULT = "artist-os/jarvis-ableton-result.v1"
ACTION_PREPARE = "prepare-writing-session"

REPO_ROOT = Path(__file__).resolve().parent
BRIDGE_PATH = REPO_ROOT / "ableton_bridge.py"


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def load_json(path: Path) -> Dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        value = json.load(handle)
    if not isinstance(value, dict):
        raise ValueError(f"Expected JSON object in {path}")
    return value


def write_json(path: Path, value: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(value, handle, indent=2)
        handle.write("\n")


def bridge_call(function_name: str, args: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    payload = json.dumps(args or {})
    proc = subprocess.run(
        [sys.executable, str(BRIDGE_PATH), function_name, payload],
        cwd=str(REPO_ROOT),
        text=True,
        capture_output=True,
        check=False,
    )

    stdout = proc.stdout.strip()
    if not stdout:
        return {
            "success": False,
            "error": f"No JSON output from ableton_bridge.py for {function_name}",
            "stderr": proc.stderr.strip(),
            "returncode": proc.returncode,
        }

    try:
        parsed = json.loads(stdout)
    except json.JSONDecodeError:
        parsed = None
        lines = [line for line in stdout.splitlines() if line.strip()]
        for index in range(len(lines)):
            candidate = "\n".join(lines[index:]).strip()
            if not candidate.startswith("{"):
                continue
            try:
                parsed = json.loads(candidate)
                break
            except json.JSONDecodeError:
                continue

        if parsed is None:
            return {
                "success": False,
                "error": f"Invalid JSON output from ableton_bridge.py for {function_name}: could not isolate a JSON object",
                "stdout": stdout,
                "stderr": proc.stderr.strip(),
                "returncode": proc.returncode,
            }

    if not isinstance(parsed, dict):
        return {
            "success": False,
            "error": f"Unexpected non-object JSON output from ableton_bridge.py for {function_name}",
            "stdout": stdout,
            "stderr": proc.stderr.strip(),
            "returncode": proc.returncode,
        }

    if proc.returncode != 0 and parsed.get("success") is not True:
        parsed.setdefault("returncode", proc.returncode)
        parsed.setdefault("stderr", proc.stderr.strip())

    return parsed


def validate_request(request: Dict[str, Any]) -> None:
    required = [
        "schemaVersion",
        "requestId",
        "action",
        "sessionId",
        "sessionFolder",
        "targetTrackName",
        "sourceMetadata",
        "options",
    ]
    missing = [key for key in required if key not in request]
    if missing:
        raise ValueError(f"Missing required request field(s): {', '.join(missing)}")

    if request["schemaVersion"] != SCHEMA_VERSION_REQUEST:
        raise ValueError(
            f"Unsupported request schemaVersion: {request['schemaVersion']} (expected {SCHEMA_VERSION_REQUEST})"
        )

    if request["action"] != ACTION_PREPARE:
        raise ValueError(f"Unsupported action: {request['action']}")

    if not isinstance(request.get("sourceMetadata"), dict):
        raise ValueError("sourceMetadata must be an object")

    if not isinstance(request.get("options"), dict):
        raise ValueError("options must be an object")



def empty_result(request: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "schemaVersion": SCHEMA_VERSION_RESULT,
        "requestId": request.get("requestId", "unknown-request"),
        "sessionId": request.get("sessionId", "unknown-session"),
        "action": ACTION_PREPARE,
        "success": False,
        "status": "failure",
        "ableton": {
            "connected": False,
            "oscOk": False,
            "diagnosticMessage": "not started",
        },
        "targetTrack": {
            "trackIndex": None,
            "name": str(request.get("targetTrackName", "Unnamed Track")),
            "created": False,
            "selected": False,
            "armed": False,
        },
        "transport": {
            "tempoBpm": request.get("bpm"),
            "applied": False,
        },
        "instrumentChoice": {
            "attempted": False,
            "loaded": False,
        },
        "starterChain": {
            "applied": False,
            "deviceResults": [],
        },
        "midiImport": {
            "requestedPaths": [request["selectedMidiPath"]] if request.get("selectedMidiPath") else [],
            "applied": False,
            "status": "unsupported-in-v1",
        },
        "warnings": [],
        "errors": [],
        "startedAt": utc_now(),
        "finishedAt": utc_now(),
    }



def find_existing_track_index(target_track_name: str) -> Optional[int]:
    find_result = bridge_call("find_track_by_name", {"query": target_track_name})
    matches = find_result.get("matches") if isinstance(find_result, dict) else None
    if isinstance(matches, list) and matches:
        top = matches[0]
        if isinstance(top, dict) and isinstance(top.get("index"), int):
            return int(top["index"])

    track_list = bridge_call("get_track_list", {})
    tracks = track_list.get("tracks") if isinstance(track_list, dict) else None
    if isinstance(tracks, list):
        for track in tracks:
            if isinstance(track, dict) and track.get("name") == target_track_name and isinstance(track.get("index"), int):
                return int(track["index"])
    return None



def create_or_resolve_track(target_track_name: str, warnings: List[str]) -> Dict[str, Any]:
    existing_index = find_existing_track_index(target_track_name)
    if existing_index is not None:
        return {
            "trackIndex": existing_index,
            "created": False,
            "selected": True,
            "armed": False,
        }

    create_result = bridge_call("create_midi_track", {"index": -1})
    if not create_result.get("success"):
        raise RuntimeError(create_result.get("message") or create_result.get("error") or "Failed to create MIDI track")

    new_index = None
    track_list = bridge_call("get_track_list", {})
    tracks = track_list.get("tracks") if isinstance(track_list, dict) else None
    if isinstance(tracks, list) and tracks:
        indices = [track.get("index") for track in tracks if isinstance(track, dict) and isinstance(track.get("index"), int)]
        if indices:
            new_index = max(indices)

    if new_index is None:
        raise RuntimeError("Track was created, but Jarvis could not resolve the new track index")

    rename_result = bridge_call("set_track_name", {"track_index": new_index, "name": target_track_name})
    if not rename_result.get("success"):
        warnings.append(rename_result.get("message") or rename_result.get("error") or "Track rename was not confirmed")

    return {
        "trackIndex": new_index,
        "created": True,
        "selected": True,
        "armed": False,
    }



def apply_transport(track_index: int, bpm: Optional[float], warnings: List[str]) -> bool:
    if bpm is None:
        warnings.append("No BPM was supplied in the request; tempo was left unchanged.")
        return False

    tempo_result = bridge_call("set_tempo", {"bpm": bpm})
    if not tempo_result.get("success"):
        warnings.append(tempo_result.get("message") or tempo_result.get("error") or "Tempo was not confirmed")
        return False
    return True



def arm_track(track_index: int, warnings: List[str]) -> bool:
    arm_result = bridge_call("arm_track", {"track_index": track_index, "armed": 1, "verify": True})
    if not arm_result.get("success"):
        warnings.append(arm_result.get("message") or arm_result.get("error") or "Track arm was not confirmed")
        return False
    return True



def get_track_device_names(track_index: int) -> List[str]:
    devices_result = bridge_call("get_track_devices", {"track_index": track_index})
    if not devices_result.get("success"):
        return []

    raw_devices = devices_result.get("devices") or devices_result.get("device_names") or []
    names: List[str] = []
    if isinstance(raw_devices, list):
        for device in raw_devices:
            if isinstance(device, dict):
                name = device.get("name") or device.get("device_name") or device.get("label")
                if name:
                    names.append(str(name))
            elif device is not None:
                names.append(str(device))
    return names


def verify_device_loaded(track_index: int, device_name: str) -> bool:
    normalized_target = device_name.lower().strip()
    lowered = [name.lower().strip() for name in get_track_device_names(track_index)]
    return any(
        normalized_target == device
        or normalized_target in device
        or device in normalized_target
        for device in lowered
    )



def apply_instrument_choice(track_index: int, request: Dict[str, Any], warnings: List[str]) -> Dict[str, Any]:
    choice = request.get("instrumentChoice")
    if not isinstance(choice, dict):
        return {"attempted": False, "loaded": False}

    name = str(choice.get("name", "")).strip() or None
    plugin_host = str(choice.get("pluginHost", "")).strip() or None
    plugin_name = str(choice.get("pluginName", "")).strip() or None
    loader_strategy = str(choice.get("loaderStrategy", "")).strip() or None
    selected_by = str(choice.get("selectedBy", "")).strip() or None
    target_label = str(choice.get("targetLabel", "")).strip() or plugin_name or name

    result = {
        "attempted": True,
        "loaded": False,
        "name": name,
        "family": choice.get("family"),
        "pluginHost": plugin_host,
        "pluginName": plugin_name,
        "loaderStrategy": loader_strategy,
        "selectedBy": selected_by,
        "message": ""
    }

    if not plugin_name:
        result["message"] = "No pluginName provided in instrumentChoice."
        warnings.append(result["message"])
        return result

    if verify_device_loaded(track_index, plugin_name) or (target_label and verify_device_loaded(track_index, target_label)):
        result["loaded"] = True
        result["message"] = f"Instrument choice already present on track: {target_label or plugin_name}"
        return result

    load_result = bridge_call("add_plugin_to_track", {"track_index": track_index, "plugin_name": plugin_name})
    loaded = bool(load_result.get("success")) and verify_device_loaded(track_index, plugin_name)
    result["loaded"] = loaded
    result["message"] = str(load_result.get("message") or load_result.get("error") or ("Loaded instrument choice" if loaded else "Instrument load failed"))

    if not loaded and target_label and target_label != plugin_name:
        alt_result = bridge_call("add_plugin_to_track", {"track_index": track_index, "plugin_name": target_label})
        alt_loaded = bool(alt_result.get("success")) and verify_device_loaded(track_index, target_label)
        if alt_loaded:
            loaded = True
            result["loaded"] = True
            result["message"] = str(alt_result.get("message") or f"Loaded instrument choice via target label: {target_label}")
        else:
            result["message"] = str(alt_result.get("message") or alt_result.get("error") or result["message"])

    if not loaded:
        warnings.append(
            f"Instrument choice '{name or plugin_name}' could not be confirmed as loaded automatically. Requested host={plugin_host}, strategy={loader_strategy}."
        )

    return result


def apply_starter_chain(track_index: int, request: Dict[str, Any], warnings: List[str]) -> Dict[str, Any]:
    starter_chain = request.get("starterChain")
    if not isinstance(starter_chain, dict):
        return {"applied": False, "deviceResults": []}

    devices = starter_chain.get("devices")
    if not isinstance(devices, list) or not devices:
        return {"applied": False, "deviceResults": []}

    results: List[Dict[str, Any]] = []
    any_loaded = False

    for device in devices[:2]:
        if not isinstance(device, dict):
            continue
        name = str(device.get("name", "")).strip()
        if not name:
            continue

        load_result = bridge_call("add_plugin_to_track", {"track_index": track_index, "plugin_name": name})
        loaded = bool(load_result.get("success"))
        verified = verify_device_loaded(track_index, name) if loaded else False
        if loaded:
          any_loaded = True
        message = load_result.get("message") or load_result.get("error") or ""
        if not loaded:
            warnings.append(f"Failed to load starter-chain device '{name}': {message}")

        results.append({
            "name": name,
            "loaded": loaded,
            "verified": verified,
            "message": message,
        })

    return {"applied": any_loaded, "deviceResults": results}



def execute_prepare_writing_session(request: Dict[str, Any]) -> Dict[str, Any]:
    result = empty_result(request)
    warnings: List[str] = result["warnings"]
    errors: List[str] = result["errors"]

    diag = bridge_call("diag_osc", {"timeout": 2.0})
    osc_ok = bool(diag.get("success"))
    result["ableton"] = {
        "connected": osc_ok,
        "oscOk": osc_ok,
        "diagnosticMessage": str(diag.get("verdict") or diag.get("message") or "No diagnostic message returned."),
    }

    if not osc_ok:
        errors.append(str(diag.get("verdict") or diag.get("message") or diag.get("error") or "Ableton OSC connectivity check failed."))
        result["finishedAt"] = utc_now()
        return result

    target_track_name = str(request["targetTrackName"])
    track_state = create_or_resolve_track(target_track_name, warnings)
    track_index = track_state["trackIndex"]
    result["targetTrack"] = {
        "trackIndex": track_index,
        "name": target_track_name,
        "created": bool(track_state["created"]),
        "selected": bool(track_state["selected"]),
        "armed": False,
    }

    tempo_applied = apply_transport(track_index, request.get("bpm"), warnings)
    result["transport"] = {
        "tempoBpm": request.get("bpm"),
        "applied": tempo_applied,
    }

    armed = arm_track(track_index, warnings)
    result["targetTrack"]["armed"] = armed

    result["instrumentChoice"] = apply_instrument_choice(track_index, request, warnings)
    if isinstance(request.get("instrumentChoice"), dict) and not result["instrumentChoice"].get("loaded"):
        errors.append(
            f"Requested instrument choice '{result['instrumentChoice'].get('name') or result['instrumentChoice'].get('pluginName') or 'unknown'}' was not confirmed as loaded."
        )
    result["starterChain"] = apply_starter_chain(track_index, request, warnings)

    result["success"] = len(errors) == 0
    result["status"] = "success" if result["success"] else "failure"
    result["finishedAt"] = utc_now()
    return result



def main() -> int:
    parser = argparse.ArgumentParser(description="artist-os -> JarvisAbleton deterministic adapter")
    parser.add_argument("--request", required=True, help="Path to artist-os request JSON")
    parser.add_argument("--response", required=True, help="Path to write adapter result JSON")
    args = parser.parse_args()

    request_path = Path(args.request).resolve()
    response_path = Path(args.response).resolve()

    request: Dict[str, Any] = {}
    result: Dict[str, Any]

    try:
        request = load_json(request_path)
        validate_request(request)
        result = execute_prepare_writing_session(request)
    except Exception as exc:
        if request:
            result = empty_result(request)
        else:
            result = {
                "schemaVersion": SCHEMA_VERSION_RESULT,
                "requestId": "unknown-request",
                "sessionId": "unknown-session",
                "action": ACTION_PREPARE,
                "success": False,
                "status": "failure",
                "ableton": {"connected": False, "oscOk": False, "diagnosticMessage": "request validation failed"},
                "targetTrack": {"trackIndex": None, "name": "Unknown Track", "created": False, "selected": False, "armed": False},
                "transport": {"applied": False},
                "starterChain": {"applied": False, "deviceResults": []},
                "midiImport": {"requestedPaths": [], "applied": False, "status": "unsupported-in-v1"},
                "warnings": [],
                "errors": [],
                "startedAt": utc_now(),
                "finishedAt": utc_now(),
            }
        result.setdefault("errors", []).append(str(exc))
        result["finishedAt"] = utc_now()

    write_json(response_path, result)
    print(json.dumps(result, indent=2))
    return 0 if result.get("success") else 1


if __name__ == "__main__":
    sys.exit(main())
